export const buildings = 
[
	{
		_id: '624ce52fbf9bc46da7ab3880',
		name: 'Exhibit',
		address: '56 Fulton Street',
		city: 'New York',
		state: 'NY',
		postal: '10038',
		plans: [
			{	
				idPlan: 1,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
			{
				idPlan: 2,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab3885',
		name: 'The Morgan',
		address: '160 Morgan Street',
		city: 'Jersey City',
		state: 'NJ',
		postal: '07302',
		plans: [
			{
				idPlan: 3,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
			{
				idPlan: 4,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab388b',
		name: 'Chelsea Stratus',
		address: '101 West 24th Street',
		city: 'New York',
		state: 'NY',
		postal: '10010',
		plans: [
			{
				idPlan: 5,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab3895',
		name: 'One Ten Third',
		address: '110 3rd Avenue',
		city: 'New York',
		state: 'NY',
		postal: '10003',
		plans: [
			{
				idPlan: 6,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab389a',
		name: '88 Leonard',
		address: '88 Leonard Street',
		city: 'New York',
		state: 'NY',
		postal: '10013',
		plans: [
			{
				idPlan: 7,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
			{
				idPlan: 8,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab38e5',
		name: '303 E 33rd',
		address: '303 East 33rd Street',
		city: 'New York',
		state: 'NY',
		postal: '10016',
		plans: [
			{
				idPlan: 9,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab38d3',
		name: '10 Rutgers',
		address: '10 Rutgers Street',
		city: 'New York',
		state: 'NY',
		postal: '10002',
		plans: [
			{
				idPlan: 10,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab38bd',
		name: 'Exhibit',
		address: '29 Cliff Street',
		city: 'New York',
		state: 'NY',
		postal: '10038',
		plans: [
			{
				idPlan: 11,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
			{
				idPlan: 12,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab38d5',
		name: 'The Jefferson',
		address: '211 East 13th Street',
		city: 'New York',
		state: 'NY',
		postal: '10003',
		plans: [
			{
				idPlan: 13,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
			{
				idPlan: 14,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab3907',
		name: '565 Broome',
		address: '565 Broome Street',
		city: 'New York',
		state: 'NY',
		postal: '10013',
		plans: [
			{
				idPlan: 15,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
		],
	},
	{
		_id: '624ce52fbf9bc46da7ab3909',
		name: '133 W 22nd',
		address: '133 West 22nd Street',
		city: 'New York',
		state: 'NY',
		postal: '10011',
		plans: [
			{
				idPlan: 16,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
			{
				idPlan: 17,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
		],
	},
	{
		_id: '624ce530bf9bc46da7ab3953',
		name: 'Exhibit',
		address: '60 Fulton Street',
		city: 'New York',
		state: 'NY',
		postal: '10038',
		plans: [
			{
				idPlan: 18,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
			{
				idPlan: 19,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
		],
	},
	{
		_id: '624ce530bf9bc46da7ab3957',
		name: '249 Broome',
		address: '249 Broome Street',
		city: 'New York',
		state: 'NY',
		postal: '10002',
		plans: [
			{
				idPlan: 20,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
			{
				idPlan: 21,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
		],
	},
	{
		_id: '624cc76a21ae7b539b98ac39',
		name: 'The Charleston',
		address: '225 East 34th Street',
		city: 'New York',
		state: 'NY',
		postal: '10016',
		plans: [
			{
				idPlan: 22,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
		],
	},
	{
		_id: '62324c06d0a8c1372303c880',
		name: 'The Anthem',
		address: '222 East 34th Street',
		city: 'New York',
		state: 'NY',
		postal: '10016',
		plans: [
			{
				idPlan: 23,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
		],
	},
	{
		_id: '624ce530bf9bc46da7ab392c',
		name: 'SoHo Court',
		address: '301 Elizabeth Street',
		city: 'New York',
		state: 'NY',
		postal: '10012',
		plans: [
			{
				idPlan: 24,
				monthsFree: 1,
				label: 'Premium',
				price: '50',
			},
			{
				idPlan: 25,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
		],
	},
	{
		_id: 1,
		name: '50 Franklin',
		address: '50 Franklin Street',
		city: 'New York',
		state: 'NY',
		postal: '10013',
		plans: [
			{
				id: 1,
				monthsFree: 0,
				label: 'Basic',
				price: '30',
			},
		],
	},
];
